<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-GCO8KQM" name="com.actitime.testscript.customerModule$TaskModule" tests="5" failures="0" timestamp="2023-05-05T15:26:41 IST" time="0.031" errors="1">
  <testcase name="modifyTask" time="0.000" classname="com.actitime.testscript.customerModule$TaskModule"/>
  <system-out>
    <![CDATA[modifyTask]]>
  </system-out>
  <testcase name="deleteTask" time="0.004" classname="com.actitime.testscript.customerModule$TaskModule">
    <error type="java.lang.Error" message="Unresolved compilation problems: 
	Syntax error on token &quot;.&quot;, delete this token
	Type mismatch: cannot convert from void to boolean
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
Syntax error on token ".", delete this token
Type mismatch: cannot convert from void to boolean

at com.actitime.testscript.customerModule$TaskModule.deleteTask(customerModule.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- deleteTask -->
  <system-out/>
  <testcase name="createTask" time="0.000" classname="com.actitime.testscript.customerModule$TaskModule"/>
  <system-out>
    <![CDATA[createTask]]>
  </system-out>
  <testcase name="createTask" time="0.010" classname="com.actitime.testscript.customerModule$TaskModule"/>
  <system-out>
    <![CDATA[createTask]]>
  </system-out>
  <testcase name="createTask" time="0.017" classname="com.actitime.testscript.customerModule$TaskModule"/>
  <system-out>
    <![CDATA[createTask]]>
  </system-out>
</testsuite> <!-- com.actitime.testscript.customerModule$TaskModule -->
